# Generated by Django 5.1.2 on 2024-10-16 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField(default=144, verbose_name='Количество часов')),
                ('title', models.CharField(choices=[('Хим', 'Химия'), ('Рус', 'Русский язык'), ('Мат', 'Математика')], default='Мат', max_length=3, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Curator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('department', models.CharField(max_length=255, verbose_name='Кафедра')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('curator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.curator', verbose_name='ФИО')),
            ],
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_number', models.CharField(max_length=10, unique=True, verbose_name='Серия и номер')),
                ('full_name', models.OneToOneField(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student', verbose_name='ФИО')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255, verbose_name='ФИО')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('start_date', models.DateField(null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(auto_now=True, verbose_name='Дата конца')),
                ('full_name', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='student.student', verbose_name='ФИО')),
            ],
        ),
    ]
